# python setup script
pip install numpy
pip install scipy
pip install pandas
pip install astropy
pip install donuts
pip install pyqt5
pip install matplotlib
pip install sep
pip install scikit-image
pip install reproject
pip install pyregion
pip install pylint
pip install pyephem
pip install jupyter
pip install jupyterthemes
pip install ccdproc
pip install statsmodels
pip install george
pip install emcee
pip install batman-package
pip install ellc
pip install flask
